### ISSUE TITLE
Request for PyPI name transfer

### ISSUE THREAD

**Issue by eladb** [harlowja/constructs#1]
Hi @harlowja,

My name is Elad and I work at AWS on the [AWS Cloud Development Kit](https://github.com/aws/aws-cdk).

As part of the AWS CDK project we have designed a programming model for composable configuration called "constructs". It is at the base of the CDK's developer experience.

Recently, we decided that we wish to extract this programming model into an independent library to enable other CDKs to be created. For example, we have opened sourced a CDK for Kubernetes called [cdk8s](https://github.com/awslabs/cdk8s) which uses constructs as well.

We wish to use the name `constructs` as the core library name and we noticed that you have published [constructs](https://pypi.org/project/constructs/) to PyPi in 2014.

We were wondering if you might be willing to transfer this name to us according to [PyPI's protocol](https://www.python.org/dev/peps/pep-0541/#how-to-request-a-name-transfer) for name transfer.

Thanks in advance.

**Comment by harlowja** [comment]
Sure, can do,
Let me do that tomorrow.

**Comment by eladb** [comment]
Thanks a lot! I am not sure if you just need to delete it so we can publish using this name or perform some kind of transfer. 

At any rate, our pypi user is [aws-cdk](https://pypi.org/user/aws-cdk) in case you need it.

Let me know, and thanks again! 🙏

**Comment by eladb** [comment]
Any updates?

**Comment by harlowja** [comment]
Should be all done, let me know if it works.

**Comment by eladb** [comment]
We got it. Thanks so much!
